---
- shell: pwd
  register: cc
- debug: var=cc
- shell: head -n1 /dir/backupip.txt
  register: ip
- lineinfile:
   path: /dir/backup.csv
   regexp: '^{{ ip.stdout }}'
   line: '{{ip.stdout}},free'
- shell: 'echo "$(tail -n +2 /dir/backupip.txt)" > /dir/backupip.txt'
