---
- shell: head -n1 /dir/webip.txt
  register: ip 
- lineinfile:
   path: /dir/web.csv
   regexp: '^{{ ip.stdout }}'
   line: '{{ip.stdout}},Allocated'
- shell: 'echo "$(tail -n +2 /dir/webip.txt)" > /dir/webip.txt' 
